name: adhawk_ble
description: Flutter package for communicating with AdHawk BLE devices
version: 0.0.1
homepage: https://www.adhawkmicrosystems.com/

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: 1.14.18
  synchronized: ^3.1.0
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  equatable: ^2.0.5
  logging: ^1.2.0
  retry: ^3.1.2
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.1
  mocktail: ^0.3.0

flutter:
